---
- name: Configure db (PostgreSQL)
  hosts: db
  become: true
  roles: 
    - graywrk.ansible_role_postgresql

- name: Configure django application
  hosts: app
  become: true
  tasks:
    - name: Run apt-get update
      ansible.builtin.apt:
        update_cache: yes